export const PLANT_DATABASE = [
  {
    id: "rose",
    name: "Rose",
    scientificName: "Rosa spp.",
    description: "A flowering plant known for its beautiful blooms and fragrance",
    characteristics: ["Red, pink, white, or yellow flowers", "Thorny stems", "Green leaves"],
    habitat: "Gardens, cultivated worldwide",
    season: "Spring to Fall",
    difficulty: "Moderate",
    waterNeeds: "Regular watering",
    sunlight: "Full sun (6+ hours)",
    image: "/red-rose.png",
    category: "plant",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    scientificName: "Helianthus annuus",
    description: "A tall plant with large yellow flowers that track the sun",
    characteristics: ["Large yellow petals", "Brown center disk", "Tall green stem"],
    habitat: "Fields, gardens, temperate regions",
    season: "Summer",
    difficulty: "Easy",
    waterNeeds: "Moderate watering",
    sunlight: "Full sun (6+ hours)",
    image: "/sunflower-yellow-flower.jpg",
    category: "plant",
  },
  {
    id: "tulip",
    name: "Tulip",
    scientificName: "Tulipa spp.",
    description: "Spring-flowering bulb with cup-shaped flowers",
    characteristics: ["Cup-shaped flowers", "Various colors", "Green stems and leaves"],
    habitat: "Gardens, temperate regions",
    season: "Spring",
    difficulty: "Easy",
    waterNeeds: "Moderate watering",
    sunlight: "Full sun to partial shade",
    image: "/colorful-tulip-flowers.jpg",
    category: "plant",
  },
  {
    id: "fern",
    name: "Fern",
    scientificName: "Polypodiopsida",
    description: "Ancient plant with feathery, delicate fronds",
    characteristics: ["Feathery fronds", "Green leaves", "No flowers"],
    habitat: "Shaded forests, moist areas",
    season: "Year-round",
    difficulty: "Easy",
    waterNeeds: "Keep soil moist",
    sunlight: "Partial to full shade",
    image: "/green-fern-fronds.jpg",
    category: "plant",
  },
  {
    id: "daisy",
    name: "Daisy",
    scientificName: "Bellis perennis",
    description: "Small flower with white petals and yellow center",
    characteristics: ["White petals", "Yellow center", "Green leaves"],
    habitat: "Meadows, grasslands, gardens",
    season: "Spring to Summer",
    difficulty: "Very Easy",
    waterNeeds: "Low to moderate",
    sunlight: "Full sun to partial shade",
    image: "/white-daisy.png",
  },
  {
    id: "lavender",
    name: "Lavender",
    scientificName: "Lavandula spp.",
    description: "Fragrant purple flowers used in aromatherapy",
    characteristics: ["Purple flowers", "Narrow leaves", "Aromatic"],
    habitat: "Mediterranean regions, gardens",
    season: "Summer",
    difficulty: "Easy",
    waterNeeds: "Low watering",
    sunlight: "Full sun",
    image: "/purple-lavender-flowers.jpg",
  },
  {
    id: "orchid",
    name: "Orchid",
    scientificName: "Orchidaceae",
    description: "Exotic flower with unique shapes and vibrant colors",
    characteristics: ["Unique petal shapes", "Various colors", "Glossy leaves"],
    habitat: "Tropical regions, greenhouses",
    season: "Year-round",
    difficulty: "Difficult",
    waterNeeds: "Moderate, well-draining",
    sunlight: "Indirect bright light",
    image: "/exotic-orchid-flower.jpg",
  },
  {
    id: "cactus",
    name: "Cactus",
    scientificName: "Cactaceae",
    description: "Desert plant with thick, fleshy stems and spines",
    characteristics: ["Thick green stems", "Sharp spines", "Minimal leaves"],
    habitat: "Desert regions, arid climates",
    season: "Year-round",
    difficulty: "Very Easy",
    waterNeeds: "Very low watering",
    sunlight: "Full sun",
    image: "/green-cactus-plant.jpg",
  },
]

export const NON_PLANT_DATABASE = [
  {
    id: "rock",
    name: "Rock",
    scientificName: "Mineral formation",
    description: "A natural stone or mineral formation found in nature",
    characteristics: ["Hard surface", "Gray or brown color", "Rough texture", "No organic features"],
    habitat: "Mountains, riverbeds, gardens",
    season: "Year-round",
    difficulty: "N/A",
    waterNeeds: "N/A",
    sunlight: "N/A",
    image: "/gray-rock-stone.jpg",
    category: "non-plant",
  },
  {
    id: "metal-can",
    name: "Metal Can",
    scientificName: "Aluminum beverage container",
    description: "An aluminum or steel beverage container commonly used for drinks",
    characteristics: ["Metallic surface", "Cylindrical shape", "Smooth and reflective", "Manufactured"],
    habitat: "Recycling bins, stores, homes",
    season: "Year-round",
    difficulty: "N/A",
    waterNeeds: "N/A",
    sunlight: "N/A",
    image: "/aluminum-metal-can.jpg",
    category: "non-plant",
  },
  {
    id: "plastic-bottle",
    name: "Plastic Bottle",
    scientificName: "Polyethylene terephthalate (PET) container",
    description: "A plastic container for liquids, commonly used for water or beverages",
    characteristics: ["Transparent or translucent", "Smooth plastic surface", "Cylindrical", "Lightweight"],
    habitat: "Stores, homes, recycling centers",
    season: "Year-round",
    difficulty: "N/A",
    waterNeeds: "N/A",
    sunlight: "N/A",
    image: "/plastic-water-bottle.jpg",
    category: "non-plant",
  },
  {
    id: "wood-block",
    name: "Wood Block",
    scientificName: "Processed timber",
    description: "A cut piece of wood or wooden cube used for construction or crafts",
    characteristics: ["Wood grain visible", "Rectangular or cubic shape", "Brown or tan color", "Hard surface"],
    habitat: "Workshops, construction sites, homes",
    season: "Year-round",
    difficulty: "N/A",
    waterNeeds: "N/A",
    sunlight: "N/A",
    image: "/wooden-block-cube.jpg",
    category: "non-plant",
  },
  {
    id: "ceramic-pot",
    name: "Ceramic Pot",
    scientificName: "Clay ceramic container",
    description: "A clay or ceramic container used for planting or storage",
    characteristics: ["Ceramic texture", "Rounded or cylindrical shape", "Porous surface", "Earthy color"],
    habitat: "Gardens, homes, plant nurseries",
    season: "Year-round",
    difficulty: "N/A",
    waterNeeds: "N/A",
    sunlight: "N/A",
    image: "/ceramic-clay-pot.jpg",
    category: "non-plant",
  },
]

export function getPlantById(id: string) {
  return PLANT_DATABASE.find((plant) => plant.id === id)
}

export function searchPlants(query: string) {
  const lowerQuery = query.toLowerCase()
  return PLANT_DATABASE.filter(
    (plant) =>
      plant.name.toLowerCase().includes(lowerQuery) ||
      plant.scientificName.toLowerCase().includes(lowerQuery) ||
      plant.description.toLowerCase().includes(lowerQuery),
  )
}

export function getNonPlantById(id: string) {
  return NON_PLANT_DATABASE.find((item) => item.id === id)
}

export function getAllDetectableItems() {
  return [...PLANT_DATABASE, ...NON_PLANT_DATABASE]
}
